"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.inBrowser = typeof window !== 'undefined';
exports.inWeex = typeof WXEnvironment !== 'undefined' && !!WXEnvironment.platform;
exports.weexPlatform = exports.inWeex && WXEnvironment.platform.toLowerCase();
var UA = exports.inBrowser && window.navigator.userAgent.toLowerCase();
exports.isIE = UA && /msie|trident/.test(UA);
exports.isIE9 = UA && UA.indexOf('msie 9.0') > 0;
exports.isEdge = UA && UA.indexOf('edge/') > 0;
exports.isAndroid = (UA && UA.indexOf('android') > 0) || (exports.weexPlatform === 'android');
exports.isiOS = (UA && /iphone|ipad|ipod|ios/.test(UA)) || (exports.weexPlatform === 'ios');
exports.isChrome = UA && /chrome\/\d+/.test(UA) && !exports.isEdge;
exports.inNodeJS = !exports.inBrowser && !exports.inWeex && typeof global !== undefined;
